# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: jekyll-agency

url: "https://healthandbeautylab.co.uk"
baseurl: "" # the subpath of your site, e.g. /blog

title: Health & Beauty Lab
tagline: Osteopathy, Pain Relief & Botox Injections in London.
email: info@healthandbeautylab.co.uk
description: Experience personalized care from our skilled mobile osteopath, massage therapist, and aesthetic injection specialist—all delivered to your doorstep.
author: Luca Lucifora
logo_height: 52
logo:
  assets/img/logo_square.webp
  # height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: G-K3MGR3BGF6

markdown: kramdown

collections:
  common-services:
  beauty-services:
  portfolio:
  integrated-care:

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/mdovvdzq"

social:
  links:
    - https://www.instagram.com/health_and_beauty_lab
    - https://www.tiktok.com/@health_and_beauty_lab
    - https://www.treatwell.co.uk/place/health-and-beauty-lab/
    - https://wa.me/447918249545

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-feed
  # - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      title: Osteopathy, Pain Relief & Boto
      keywords: Low Back Pain, Muscle Strai, Dry Needlin, Cosmetic Filte, Anti Wrinkle Treatment, Botox Injectable, UK, London
